### PR TITLE
Bound map size in kMap

### PR DESCRIPTION
**Pull request by akalin-keybase**
This is done in the fast paths already.

### CODE REVIEW

**Review by maxtaco — APPROVED** [review]

**Comment by maxtaco** [comment]
this PR has broken github

screen shot 2018-09-20 at 9 26 25 am

**Comment by maxtaco** [comment]
this PR has broken github

screen shot 2018-09-20 at 9 26 25 am

**Comment by maxtaco** [comment]
this PR has broken github

screen shot 2018-09-20 at 9 26 25 am

**Review by maxtaco — APPROVED** [review]

**Comment by akalin-keybase** [comment]
Diff looks fine now, I assume it worked for you since you approved!

**Pull request merged**
